### PR TITLE
Fixes for MELPA

### PR DESCRIPTION
**Pull request by Chobbes**
- Added w3m require.
- Fixed typos.
- Fixed some setqs that were not in "gopher-" namespace.
- Fixed some indentation.

Let's get this thing on MELPA :).

### CODE REVIEW

**Comment by Chobbes** [comment]
I believe this fixes most of the issues brought up in: https://github.com/melpa/melpa/pull/6021 (which haven't already been fixed).

The only issue that this doesn't address is this one:

> The [ and ] keyboard shortcuts seem to cause gopher-mode to lock up on me (looks like I'm stuck in the loop around line 391).

The `[` and `]` keys don't seem to lock up for me but I don't know how they differ from `end-of-buffer` and `beginning-of-buffer`, so I'm not sure they work as expected. I didn't touch these at all, though.

**Comment by gum3n** [comment]
@Chobbes keys `[` and `]` are not for navigating between end and beginning of buffer. They are used to jump between links of type `0`. Those links are used for text files [text files](https://en.wikipedia.org/wiki/Gopher_%28protocol%29#Item_types)

**Comment by Chobbes** [comment]
Ah, gotcha, my confusion was in trying to navigate sub-menus with this.

**Comment by msnyder-info** [comment]
Thank you for your contribution!

**Pull request merged**
